### ISSUE TITLE
Future updates

### ISSUE THREAD

**Issue by kobzar** [Makrennel/hyprland-void#3]
Thanks one more time for this repo for Void users
But one simple question is actual for me

Could you make/add instruction for update Hyprland in future by this install method?

**Comment by Makrennel** [comment]
It's not really possible to auto update Hyprland because of how quickly development moves/has moved. Dependencies change and the template would probably break pretty quickly if it were pulling directly from git. Whenever Hyprland puts out a new tagged release I will try to update to meet it, although I can't guarantee it. If this repository updates though, you only have to

```
git pull
```
and 
```
cp -r srcpkgs/* ~/void-packages/srcpkgs/*
```
again. On some occasions if the shlibs change you may have to manually update the two added lines in ~/void-packages/common/shlibs to whatever the new values are in hyprland-void/common/shlibs, but this is pretty simple to do.

**Comment by kobzar** [comment]
thanks
Could you add to this repo another hyprland packages? Like hyprpaper e.t.c.?

**Comment by Makrennel** [comment]
Hyprpaper is already in the repo, I might add some other packages later, but most things in the void linux repos for sway or wlroots should work fine.
