### ISSUE TITLE
Why don't you ask for a merge to void-packages?

### ISSUE THREAD

**Issue by not-NEKO** [Makrennel/hyprland-void#59]
Title.

**Comment by soanvig** [comment]
https://github.com/void-linux/void-packages/issues/37544

**Comment by Makrennel** [comment]
Void is taking an anti-vendoring stance and doesn't like it when programs don't use system-wide dependencies (like wlroots).

I've been looking at possibly trying to sign a third party binary repository to host through GitHub that users can use directly through XBPS...

But learning to write an action so that it can just automatically build, sign and push to the repository is kinda a bitch, so that might take a while.

**Comment by Makrennel** [comment]
> I've been looking at possibly trying to sign a third party binary repository to host through GitHub that users can use directly through XBPS...
> 
> But learning to write an action so that it can just automatically build, sign and push to the repository is kinda a bitch, so that might take a while.

Well, I did it - instructions in README for how to add the repo.
