### ISSUE TITLE
Hyprland 0.42 update braked the window manager for me as Nvidia user

### ISSUE THREAD

**Issue by binarylinuxx** [Makrennel/hyprland-void#76]
In My grub config I'm added required modules 
GRUB_CMD_LINE="nvidia_drm.modeset=1 acpi=off".
Logs if I'm trying run Hyprland:
one.uld not find a Gpu or encountered some issues.
I'm already added my user to "_seatd" and "video" groups,
Thanks for any help.

**Comment by Makrennel** [comment]
Add 

```
debug {
  disable_logs = false
  enable_stdout_logs = true
}
```

To your config and show the logs.

**Comment by binarylinuxx** [comment]
> Add 
> 
> ```
> debug {
>   disable_logs = false
>   enable_stdout_logs = true
> }
> ```
> 
> To your config and show the logs.

Can I use "wgetpaste" to share the logs?

**Comment by binarylinuxx** [comment]
> Add 
> 
> ```
> debug {
>   disable_logs = false
>   enable_stdout_logs = true
> }
> ```
> 
> To your config and show the logs.

Ok I'm used wgetpaste the logs https://bpa.st/NHTA

**Comment by Makrennel** [comment]
> Ok I'm used wgetpaste the logs https://bpa.st/NHTA

The logs suggest you don't have GPU drivers installed. If that's not the problem this might be an error which was fixed upstream in Aquamarine git and Hyprland git. It's probably not relating to this package, but unfortunately you might have to downgrade and stick to 0.41.2 for a while because after 0.42.0 Hyprland has switched to requiring a newer version of GCC than is available on void linux right now, so you won't actually be able to build it from git.
